services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres1
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-init:
    image: apache/airflow:2.5.0
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com",
      ]
    restart: on-failure

  webserver:
    image: apache/airflow:2.5.0
    container_name: airflow_webserver1
    depends_on:
      - postgres
      - airflow-init
    environment:
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/config/gcs_config.json # ✅ Thêm biến môi trường GCS
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./config:/opt/airflow/config
      - ./etl:/opt/airflow/etl
      - ./data:/opt/airflow/data
      - ./config/gcs_config.json:/opt/airflow/config/gcs_config.json # ✅ Mount file key vào container
    command: ["airflow", "webserver"]
    restart: always

  scheduler:
    image: apache/airflow:2.5.0
    container_name: airflow_scheduler1
    depends_on:
      - webserver
    environment:
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/config/gcs_config.json # ✅ Thêm biến môi trường GCS
    volumes:
      - ./dags:/opt/airflow/dags
      - ./config:/opt/airflow/config
      - ./etl:/opt/airflow/etl
      - ./data:/opt/airflow/data
      - ./config/gcs_config.json:/opt/airflow/config/gcs_config.json # ✅ Mount file key vào container
    command: ["airflow", "scheduler"]
    restart: always

volumes:
  postgres_data:
